import type { Metadata } from 'next'

import { fontHeading, fontMono, fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'

import Providers from './providers/providers'

import './globals.css'

export const metadata: Metadata = {
	title: 'Snowboard City',
	description: 'Generated by create next app',
}

interface LayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
					fontMono.variable,
					fontHeading.variable,
				)}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
