import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import type { Metadata } from 'next'

import { fontHeading, fontMono, fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'
import Providers from '@/providers/providers'

import './globals.css'

export const runtime = 'edge'

export const metadata: Metadata = {
	title: 'Snowboard City',
	description: 'Generated by create next app',
}

interface LayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang="en">
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
					fontMono.variable,
					fontHeading.variable,
				)}
				suppressHydrationWarning
			>
				<Providers>
					{children}
					<Analytics />
					<SpeedInsights />
				</Providers>
			</body>
		</html>
	)
}
