// Generated by ts-to-zod
import { z } from 'zod'

import { imageSchema, moneySchema, seoSchema } from './shopify.schema'

export const shopifyCartSchema = z.object({
	id: z.string(),
	checkoutUrl: z.string(),
	cost: z.object({
		subtotalAmount: moneySchema,
		totalAmount: moneySchema,
		totalTaxAmount: moneySchema,
	}),
	lines: z.any(),
	totalQuantity: z.number(),
})

export const cartItemSchema = z.object({
	id: z.string(),
	quantity: z.number(),
	cost: z.object({
		totalAmount: moneySchema,
	}),
	merchandise: z.object({
		id: z.string(),
		title: z.string(),
		selectedOptions: z.array(
			z.object({
				name: z.string(),
				value: z.string(),
			}),
		),
		product: z.object({
			id: z.string(),
			handle: z.string(),
			availableForSale: z.boolean(),
			title: z.string(),
			description: z.string(),
			descriptionHtml: z.string(),
			options: z.array(
				z.object({
					id: z.string(),
					name: z.string(),
					values: z.array(z.string()),
				}),
			),
			priceRange: z.object({
				maxVariantPrice: moneySchema,
				minVariantPrice: moneySchema,
			}),
			variants: z.array(
				z.object({
					id: z.string(),
					title: z.string(),
					availableForSale: z.boolean(),
					selectedOptions: z.array(
						z.object({
							name: z.string(),
							value: z.string(),
						}),
					),
					price: moneySchema,
				}),
			),
			featuredImage: imageSchema,
			images: z.array(imageSchema),
			seo: seoSchema,
			tags: z.array(z.string()),
			updatedAt: z.string(),
		}),
	}),
})

export const shopifyCartOperationSchema = z.object({
	data: z.object({
		cart: z.object({
			id: z.string(),
			checkoutUrl: z.string(),
			cost: z.object({
				subtotalAmount: moneySchema,
				totalAmount: moneySchema,
				totalTaxAmount: moneySchema,
			}),
			lines: z.any(),
			totalQuantity: z.number(),
		}),
	}),
	variables: z.object({
		cartId: z.string(),
	}),
})

export const shopifyCreateCartOperationSchema = z.object({
	data: z.object({
		cartCreate: z.object({
			cart: z.object({
				id: z.string(),
				checkoutUrl: z.string(),
				cost: z.object({
					subtotalAmount: moneySchema,
					totalAmount: moneySchema,
					totalTaxAmount: moneySchema,
				}),
				lines: z.any(),
				totalQuantity: z.number(),
			}),
		}),
	}),
})

export const shopifyAddToCartOperationSchema = z.object({
	data: z.object({
		cartLinesAdd: z.object({
			cart: z.object({
				id: z.string(),
				checkoutUrl: z.string(),
				cost: z.object({
					subtotalAmount: moneySchema,
					totalAmount: moneySchema,
					totalTaxAmount: moneySchema,
				}),
				lines: z.any(),
				totalQuantity: z.number(),
			}),
		}),
	}),
	variables: z.object({
		cartId: z.string(),
		lines: z.array(
			z.object({
				merchandiseId: z.string(),
				quantity: z.number(),
			}),
		),
	}),
})

export const shopifyRemoveFromCartOperationSchema = z.object({
	data: z.object({
		cartLinesRemove: z.object({
			cart: z.object({
				id: z.string(),
				checkoutUrl: z.string(),
				cost: z.object({
					subtotalAmount: moneySchema,
					totalAmount: moneySchema,
					totalTaxAmount: moneySchema,
				}),
				lines: z.any(),
				totalQuantity: z.number(),
			}),
		}),
	}),
	variables: z.object({
		cartId: z.string(),
		lineIds: z.array(z.string()),
	}),
})

export const shopifyUpdateCartOperationSchema = z.object({
	data: z.object({
		cartLinesUpdate: z.object({
			cart: z.object({
				id: z.string(),
				checkoutUrl: z.string(),
				cost: z.object({
					subtotalAmount: moneySchema,
					totalAmount: moneySchema,
					totalTaxAmount: moneySchema,
				}),
				lines: z.any(),
				totalQuantity: z.number(),
			}),
		}),
	}),
	variables: z.object({
		cartId: z.string(),
		lines: z.array(
			z.object({
				id: z.string(),
				merchandiseId: z.string(),
				quantity: z.number(),
			}),
		),
	}),
})

export const cartSchema = shopifyCartSchema.omit({ lines: true }).and(
	z.object({
		lines: z.array(cartItemSchema),
	}),
)

export const updateCartItemFormSchema = z.object({
	quantity: z.number().min(0).default(1),
})
