// Generated by ts-to-zod
import { z } from 'zod'

export const menuSchema = z.object({
	title: z.string(),
	href: z.string(),
})

export const shopifyMenuOperationSchema = z.object({
	data: z.object({
		menu: z
			.object({
				items: z.array(
					z.object({
						title: z.string(),
						url: z.string(),
					}),
				),
			})
			.optional(),
	}),
	variables: z.object({
		handle: z.string(),
	}),
})
